/** Every word a report's tables and charts show, per language. Prose is the
 *  agent's; these are the renderer's, so the same term reads the same way in
 *  every report. Keep in step with the glossary in the perf-report skill's
 *  TEMPLATE.md. */

export type Lang = 'en' | 'zh'

const en = {
  baseline: 'Baseline',
  optimized: 'Optimized',
  optimizedN: 'Optimized {n}',
  sweep: 'Input {inp} / output {out}',
  agentic: 'Agentic dataset (concurrency {c})',
  concurrency: 'concurrency',
  atConcurrency: '@ concurrency {c}',
  tps: 'tok/s',
  scenario: 'Scenario',
  benchmark: 'Benchmark',
  setting: 'Setting',
  workload: 'Workload',
  method: 'How it is measured',
  item: 'Item',
  value: 'Value',
  model: 'Model',
  precision: 'Precision',
  hardware: 'Hardware',
  hardwareValue: '{n}× {card} per server',
  image: 'Image',
  slo: 'SLO',
  sloValue: 'TTFT {pct} ≤ {ms} ms, ≥ {tps} tok/s per request',
  summaryTitle: 'Normalized throughput at the best concurrency within SLO',
  totalPerGpu: 'Normalized throughput (tok/s)',
  config: 'Configuration',
  bestConcurrency: 'Best concurrency within SLO',
  totalServing: 'Normalized throughput (tok/s)',
  gpusCol: 'GPUs per instance',
  bestMark: 'best {c}',
  category: 'Category',
  metric: 'Metric',
  constraint: 'Constraint or objective',
  definition: 'Definition',
  objective: 'Optimization objective',
  ttftMetric: 'TTFT {pct}',
  ttftLimit: '≤ {ms} ms',
  ttftDefinition: 'Time to first token at the {pct} percentile: the wait between sending a '
    + 'request and receiving its first token, including transmission, queueing on the server and '
    + 'processing the input. It says how soon an answer starts, not how long it takes to finish.',
  otpsMetric: 'Per-request generation speed (OTPS / request)',
  otpsLimit: '≥ {tps} tok/s per request',
  otpsDefinition: 'Output tokens one request receives per second: the whole server\u2019s output '
    + 'tokens per second divided by the requests it serves at the same time. Higher means the '
    + 'answer is written out faster.',
  objectiveMetric: 'Normalized throughput',
  objectiveLimit: 'Maximize within the SLO',
  objectiveDefinition: 'Input and output tokens processed per second, scaled to 8 GPUs so that '
    + 'configs on different GPU counts compare: a config served on N GPUs is multiplied by 8/N. '
    + 'For each scenario and config, the concurrency with the highest normalized throughput that '
    + 'still meets both constraints above is chosen, and the throughput measured there is reported.',
  sloNote: 'The SLO (service level objective) is what the serving must still feel like to a user; '
    + 'the optimization objective is what is maximized while it holds.',
  ioTokens: 'Input / output (tokens)',
  ioValue: '{inp} / {out}',
  stands: 'What it stands for',
  defaultSweep: 'Random prompts of this shape, concurrency searched up to {max}.',
  defaultAgentic: 'Recorded agentic requests, replayed at a fixed concurrency of {c}.',
  qualityWorkload: 'fixed question set',
  randomNote: 'A sweep sends random prompts of the stated input and output length, not recorded traffic.',

  ttftAxis: 'TTFT {pct} (ms)',
  sloLine: 'SLO: TTFT {pct} ≤ {ms} ms',
  bestMarks: 'dashed: best concurrency within SLO',
  throughputPanel: 'Normalized throughput (tok/s)',
  sweepThroughput: '{name}: throughput',
  sweepLatency: '{name}: latency',
  totalPanel: 'Normalized throughput (tok/s)',
  outputPanel: 'Normalized output throughput (tok/s)',
  tpotAxis: 'TPOT {pct} (ms)',
  percentile: 'Percentile',
  ttftPanel: 'Time to first token (ms)',
  inputUncached: 'input (uncached)',
  inputCached: 'input (cached)',
  output: 'output',
  workloadSweep: 'random prompts, {inp} input / {out} output tokens',
  methodSweep: 'concurrency search (up to {max}); best concurrency within SLO',
  workloadAgentic: '{n} agentic requests',
  methodAgentic: 'replayed at concurrency {c}',
  quality: 'Quality',
  absChange: 'Absolute change',
  relChange: 'Relative change',
  points: 'percentage points',
  accuracy: 'accuracy on a fixed question set',
  qualityNote: 'Quality is measured so a faster config is not a worse one: every config answers the '
    + 'same question set, and the scores are compared to the baseline\u2019s.',
  sweepNote: 'A sweep raises concurrency and reports the level with the highest throughput that '
    + 'still meets the SLO, so each config is read at its own best concurrency.',
  agenticNote: 'The agentic dataset runs at one fixed concurrency, so the SLO does not pick its level.',
  capacityNote: 'Throughput is normalized to 8 GPUs. These are serving capacities, each '
    + 'configuration at its own best concurrency within the SLO \u2014 not per-request speedups.',
  figSummary: 'Figure {n}. Normalized throughput across scenarios ({hw}).',
  figSummaryRead: 'Each configuration is read at its own best concurrency within the SLO.',
  figSweep: 'Figure {n}. Throughput and latency against concurrency: {name}.',
  figSweepRead: 'The first chart shows normalized throughput and normalized output throughput; the second '
    + 'shows TTFT and TPOT at the percentile selected above it. Dashed lines mark each '
    + 'configuration\u2019s best concurrency within the SLO.',
  figAgentic: 'Figure {n}. {name}.',
  figAgenticRead: 'Input throughput (uncached and cached) and output throughput, and TTFT at p50, '
    + 'p90 and p99; the change against the baseline is on each bar.',
  tabSummary: 'Table {n}. Best measured operating point within the SLO, per scenario and configuration.',
  tabQuality: 'Table {n}. Answer quality on a fixed question set.',
  copy: 'Copy',
  copied: 'Copied',
  unknownBlock: 'This block could not be drawn: {why}',
  noData: 'not measured',
  identical: 'identical launch settings',
  diffNote: 'Only the settings that differ are listed. A \u201c\u2014\u201d means the setting was not '
    + 'given, so the engine\u2019s own default for that version applies.',
}

type Strings = typeof en

const zh: Strings = {
  baseline: '基线',
  optimized: '优化配置',
  optimizedN: '优化配置 {n}',
  sweep: '输入 {inp} / 输出 {out}',
  agentic: 'Agentic 数据集(并发 {c})',
  concurrency: '并发',
  atConcurrency: '@ 并发 {c}',
  tps: 'tok/s',
  scenario: '场景',
  benchmark: '评测',
  setting: '参数',
  workload: '负载',
  method: '测法',
  item: '项目',
  value: '值',
  model: '模型',
  precision: '精度',
  hardware: '硬件',
  hardwareValue: '每个服务 {n}× {card}',
  image: '镜像',
  slo: 'SLO',
  sloValue: 'TTFT {pct} ≤ {ms} ms,每请求 ≥ {tps} tok/s',
  summaryTitle: 'SLO 内最佳并发下的归一化吞吐',
  totalPerGpu: '归一化吞吐(tok/s)',
  config: '配置',
  bestConcurrency: 'SLO 内最佳并发',
  totalServing: '归一化吞吐(tok/s)',
  gpusCol: '单实例卡数',
  bestMark: '最佳 {c}',
  category: '类别',
  metric: '指标',
  constraint: '约束或目标',
  definition: '定义',
  objective: '优化目标',
  ttftMetric: 'TTFT {pct}',
  ttftLimit: '≤ {ms} ms',
  ttftDefinition: '{pct} 分位的首 token 延迟:从客户端发出请求到收到第一个 token 的等待时间,'
    + '包含请求传输、服务端排队和输入处理。它衡量回答开始得多快,不代表回答写完需要多久。',
  otpsMetric: '单请求生成速度(OTPS / request)',
  otpsLimit: '每请求 ≥ {tps} tok/s',
  otpsDefinition: '单个请求平均每秒收到的输出 token 数:整机每秒输出的 token 数除以同时处理的请求数。'
    + '数值越高,回答写出来得越快。',
  objectiveMetric: '归一化吞吐',
  objectiveLimit: '满足 SLO 前提下最大化',
  objectiveDefinition: '每秒处理的输入与输出 token 总数,折算到 8 张卡,使卡数不同的配置可以直接比较:'
    + '使用 N 张卡的配置乘以 8/N。对每个场景、每组配置,选取同时满足上述两项约束且归一化吞吐最高的实测并发,'
    + '并报告该并发下测得的吞吐。',
  sloNote: 'SLO(服务水平目标)是服务必须保持的体验下限,优化目标是在守住 SLO 的前提下要最大化的指标。',
  ioTokens: '输入 / 输出(token)',
  ioValue: '{inp} / {out}',
  stands: '场景含义',
  defaultSweep: '该长度的随机 prompt,并发搜索上限 {max}。',
  defaultAgentic: '录制的 agentic 请求,固定并发 {c} 回放。',
  qualityWorkload: '固定题集',
  randomNote: '并发扫描使用指定输入/输出长度的随机 prompt,不是录制的真实流量。',

  ttftAxis: 'TTFT {pct}(ms)',
  sloLine: 'SLO:TTFT {pct} ≤ {ms} ms',
  bestMarks: '虚线:SLO 内最佳并发',
  throughputPanel: '归一化吞吐(tok/s)',
  sweepThroughput: '{name}:吞吐',
  sweepLatency: '{name}:延迟',
  totalPanel: '归一化吞吐(tok/s)',
  outputPanel: '归一化输出吞吐(tok/s)',
  tpotAxis: 'TPOT {pct}(ms)',
  percentile: '分位',
  ttftPanel: '首 token 延迟(ms)',
  inputUncached: '输入(未命中缓存)',
  inputCached: '输入(命中缓存)',
  output: '输出',
  workloadSweep: '随机 prompt,输入 {inp} / 输出 {out} tokens',
  methodSweep: '并发自动搜索(上限 {max}),取 SLO 内最佳并发',
  workloadAgentic: '{n} 条 agentic 请求',
  methodAgentic: '并发 {c} 回放',
  quality: '质量',
  absChange: '绝对变化',
  relChange: '相对变化',
  points: '个百分点',
  accuracy: '固定题集上的准确率',
  qualityNote: '质量测试用于确认更快的配置不会变差:每个配置回答同一套题目,分数与基线对比。',
  sweepNote: '并发扫描会逐步提高并发,取仍满足 SLO 的最高吞吐档位,因此每个配置都在各自的最佳并发下比较。',
  agenticNote: 'Agentic 数据集使用固定并发,其档位不由 SLO 选出。',
  capacityNote: '吞吐统一归一化到 8 卡。这些数值是服务容量,各配置取其自身的 SLO 内最佳并发,并非单请求加速比。',
  figSummary: '图 {n} · 各场景的归一化吞吐({hw})。',
  figSummaryRead: '各配置均取其自身的 SLO 内最佳并发。',
  figSweep: '图 {n} · {name}:吞吐与延迟随并发的变化。',
  figSweepRead: '第一张图为归一化吞吐与归一化输出吞吐,第二张图为上方所选分位的 TTFT 与 TPOT;虚线标出各配置的 SLO 内最佳并发。',
  figAgentic: '图 {n} · {name}。',
  figAgenticRead: '输入吞吐(未命中/命中缓存)、输出吞吐,以及 p50、p90、p99 的 TTFT;柱上标注相对基线的变化。',
  tabSummary: '表 {n} · 各场景、各配置在 SLO 内测得的最佳工作点。',
  tabQuality: '表 {n} · 固定题集上的回答质量。',
  copy: '复制',
  copied: '已复制',
  unknownBlock: '此区块无法绘制:{why}',
  noData: '未测',
  identical: '启动参数相同',
  diffNote: '表中只列出有差异的参数。\u201c\u2014\u201d 表示没有显式设置,实际取值为该引擎版本的默认值。',
}

const TABLE: Record<Lang, Strings> = { en, zh }

export type StringKey = keyof Strings

export function tr(lang: Lang, key: StringKey, vars: Record<string, string | number> = {}): string {
  const text = (TABLE[lang] ?? en)[key]
  return text.replace(/\{(\w+)\}/g, (_m, name) => (name in vars ? String(vars[name]) : `{${name}}`))
}
