"""initial schema — materialized from model metadata.

The baseline revision creates whatever app.db.models declares today, rather
than a hand-written table list that would have to be kept in step with it.
The next schema change should be a proper autogenerated incremental revision
on top of this one.

Note for anyone upgrading a database that predates this file: this is a fresh
chain, not a continuation of an older one. See docs/upgrading.md.

Revision ID: 001_initial
Revises:
Create Date: 2026-09-22
"""

from alembic import op
from app.db import models  # noqa: F401  — register tables on Base.metadata
from app.db.base import Base

revision = "001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
