/** English display strings.
 *
 *  The source of truth for what a key means. `zh.ts` mirrors this shape exactly;
 *  a key present here and missing there falls back to the English text, which is
 *  why the two files must stay structurally parallel rather than diverging into
 *  different groupings.
 *
 *  What is deliberately NOT here: metric keys, run statuses, engine arguments,
 *  benchmark slugs, machine names. Those are identifiers. They are rendered
 *  verbatim in both languages.
 */
export default {
  reports: {
    title: 'Reports',
    subtitle: 'Performance reports an agent wrote from finished runs: one baseline, the '
      + 'attempts chosen for it, and the platform\'s own comparison frozen alongside.',
    empty: 'No reports yet. Agents save them through the agent API '
      + '(POST /api/agent/v1/reports); see docs/api/agent-api.md.',
    baseline: 'Baseline run',
    attempts: 'Attempts',
    campaign: 'Campaign',
    group: 'Group',
    by: 'Saved by',
    when: 'Saved',
    notComparable: 'not comparable',
    notComparableHint: 'The platform would not have compared these runs on its own; '
      + 'the report was saved over its objection.',
    open: 'Open',
    back: 'All reports',
    inputs: 'Built from runs',
    generator: 'Generated by',
    download: 'Download source (.zip)',
    downloadHint: 'Markdown, data and renderer — everything needed to render the report elsewhere',
    loading: 'Loading…',
    missing: 'No such report.',
    exportHtml: 'Export HTML',
    exported: 'HTML exported',
    exportFailed: 'Export failed',
    language: 'Language',
  },
  nav: {
    campaigns: 'Campaigns',
    searchSpaces: 'Search spaces',
    objectives: 'Objectives',
    policies: 'Policies',
    tuning: 'Automatic Tuning',
    baselines: 'Baselines',
    runs: 'Runs',
    resources: 'Resources',
    apiKeys: 'API keys',
    reports: 'Reports',
    logOut: 'Log out',
    account: 'Account',
    signedInAs: 'Signed in as',
    language: 'Language',
  },

  account: {
    title: 'Account',
    publish: {
      title: 'Published name',
      nameField: 'Published as',
      nameNote: 'The name your submissions appear under on the benchmark platform. '
        + 'Defaults to your username. A display name you choose, not an identity the '
        + 'platform checks.',
      nameSave: 'Save name',
      nameClear: 'Use my username',
      nameSaved: 'Published name saved',
      nameCleared: 'Back to your username',
      note: 'Optional. Submissions the platform makes on your behalf are listed under '
        + 'this name.',
      saveFailed: 'Could not save the published name',
    },
    profile: 'Profile',
    role: 'Role',
    manageKeys: 'Manage API keys',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    tokenNote:
      'Your current session keeps working. API keys are separate credentials and are '
      + 'unaffected — revoke those on the API keys page.',
    needCurrent: 'Enter your current password',
    tooShort: 'At least 6 characters',
    mismatch: 'The two new passwords differ',
    sameAsOld: 'That is the password you already have',
    changed: 'Password changed',
    changeFailed: 'Could not change the password',
    users: 'Users',
    usersNote: 'admins can lease machines, mint API keys and change roles',
    promote: 'Make admin',
    demote: 'Make user',
    lastAdmin: 'The only admin — promote someone else first',
    roleChanged: '{user} is now {role}',
    roleFailed: 'Could not change the role',
  },

  common: {
    cancel: 'Cancel',
    save: 'Save',
    close: 'Close',
    copy: 'Copy',
    download: 'Download',
    refresh: 'Refresh',
    stop: 'Stop',
    id: 'ID',
    name: 'Name',
    status: 'Status',
    created: 'Created',
    started: 'Started',
    took: 'Took',
    model: 'Model',
    machine: 'Machine',
    config: 'Config',
    none: 'none',
  },



  login: {
    tagline: 'Automatic deployment tuning for LLM inference services.',
    username: 'Username',
    password: 'Password',
    logIn: 'Log in',
    createAccount: 'Create account',
    haveAccount: 'Have an account? Log in',
    newHere: 'New here? Create an account',
    failed: 'Request failed',
  },

  campaigns: {
    title: 'Campaigns',
    newCampaign: 'New campaign',
    running: '{n} running',
    waiting: ', {n} waiting for tonight',
    window: 'Window',
    search: 'Search',
    oneOff: 'one-off window',
    manual: 'manual',
  },



  runs: {
    title: 'Runs',
    campaign: 'Campaign',
    failure: 'Failure',
    container: 'Container',
    submission: 'LLMBench sub',
    stopTitle: 'Stop run',
    stopConfirm:
      'Stop run {id}? Its container will be torn down and the machine released.',
    stopIt: 'Stop it',
    stopRequested: 'Stop requested — applied within one worker tick',
    stopFailed: 'Stop failed',
    // The embeddable runs table + run drawer (components/CampaignRuns.vue).
    run: 'Run',
    count: '{n} run(s)',
    none: 'No run yet — one starts when a machine of the right card type is free.',
    logs: 'Logs',
    status: 'Status',
    gpus: 'GPUs',
    endpoint: 'Endpoint',
    started: 'Started',
    took: 'Took',
    stop: 'Stop',
    launchCommand: 'Launch command',
    notLaunched: '(not launched yet)',
    config: 'Config',
    results: 'Results',
    source: 'Source',
    passed: 'Passed',
    metrics: 'Metrics',
    metricCount: '{n} metrics',
    noMetrics: 'none',
    noResults: 'No result yet.',
    error: 'Error',
    capturedLog: 'Captured log',
    logWhileLive: 'Run still live: the log so far.',
    yes: 'yes',
    no: 'no',
  },

  campaign: {
    // The chrome of the detail page. The explanatory prose inside each tab is
    // still English only — see docs; it is the next slice, not a forgotten one.
    evaluated: '{done}/{total} candidates evaluated',
    grid: 'grid',
    objective: 'objective',
    enumerates: 'every configuration, in order',
    policy: 'policy',
    report: 'Report',
    logs: 'Logs',
    exportYaml: 'Export YAML',
    more: 'More',
    clone: 'Clone',
    cloneName: 'Name for the copy — it keeps this campaign\'s definition, not its results',
    cloneFailed: 'Clone failed',
    rerunFailedOne: 'Re-run {n} failed config',
    rerunFailedMany: 'Re-run {n} failed configs',
    pause: 'Pause',
    forceStop: 'Force stop',
    forceStart: 'Force start',
    resumeSchedule: 'Resume schedule',
    start: 'Start',
    tabs: {
      leaderboard: 'Leaderboard',
      runs: 'Runs',
      configuration: 'Configuration',
      candidates: 'Candidates',
    },
    verifiedOn: 'Verified on real traffic',
    // The lower board in a two-stage campaign: every candidate, screened. Neutral
    // wording so a single-stage campaign's one board is never titled "Screening".
    screening: 'All candidates',
    replayedOn: 'Replayed',
    datasetAdopted: 'adopted',
    otherDataset: 'other dataset',
    vsBaseline: 'vs baseline',
    baselineRow: 'baseline',
    redlines: 'Redlines',
    held: 'held',
    crossed: 'crossed',
    noRuns: 'No successful benchmarked runs yet.',
    run: 'Run',
    sweptParameters: 'Swept parameters',
    notPlanned: '{n} configurations, expanded on the first run.',
    editSchedule: 'Edit schedule',
    addSchedule: 'Add a schedule',
    exportTitle: 'Campaign as YAML',
    exportNote:
      'Inputs only — status, the current window and any override are left out, so this '
      + 'recreates the campaign rather than resurrecting a half-finished night.',
    yamlCopied: 'YAML copied',
    reportCopied: 'Report copied',
    copyMarkdown: 'Copy markdown',
    reportTitle: 'Campaign report',
  },
  baselines: {
    tuneFromThis: 'Tune from this',
  },
}

